<?xml version="1"?>
<!DOCTYPE NEWSPAPER [
<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>
<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>
]>

<NEWSPAPER>
    <ARTICLE AUTHOR="Sagar Shrestha" EDITOR="Lakpa Sherpa" DATE="09/12/2020">
        <HEADLINE>KP Oli le rajinama diye</HEADLINE>
        <BYLINE>Something</BYLINE>
        <LEAD>Aakash Raj Shakya</LEAD>
        <BODY>KP Sharma oli le Prachanda ko pressure ma rajinama diye</BODY>
        <NOTES>Some Note</NOTES>
    </ARTICLE>
</NEWSPAPER>
